---
- name: load flathub remote
  become: true
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: add vscodium repository
  become: true
  yum_repository:
    name: vscodium
    description: VS Codium
    baseurl: https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/
    gpgkey: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    gpgcheck: true
  notify: update DNF cache

- name: add RPMFusion repositories
  become: true
  dnf:
    disable_gpg_check: true
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  when: "'rpmfusion-free-release' not in ansible_facts.packages or 'rpmfusion-nonfree-release' not in ansible_facts.packages"
  notify: update DNF cache
