---
- name: set hostname
  become: true
  hostname:
    name: posterdati

- name: set RTC in universal time
  become: true
  timezone:
    hwclock: UTC

- name: install system tools
  become: true
  dnf:
    name:
      - gnome-tweaks
      - seahorse

- name: add things to grub command line
  become: true
  template:
    src: grub.j2
    dest: /etc/default/grub
    owner: root
    group: root
    mode: 0644
  notify: update grub

- name: disable auto updates
  dconf:
    key: "{{ item }}"
    value: "false"
  loop:
    - "/org/gnome/software/allow-updates"
    - "/org/gnome/software/download-updates"
    - "/org/gnome/software/download-updates-notify"

- name: save session on logout
  dconf:
    key: "/org/gnome/gnome-session/auto-save-session"
    value: "true"
