---
- name: install apps
  become: true
  dnf:
    name:
      - telegram-desktop
      - transmission
      - transmission-remote-gtk

- name: install games
  become: True
  dnf:
    name:
      - aisleriot

- name: install CLI tools
  become: true
  dnf:
    name:
      - android-tools
      - ansible
      - aria2
      - bind-utils
      - fdupes
      - htop
      - iftop
      - ncdu
      - nmap
      - pandoc
      - pre-commit
      - ranger
      - rclone
      - traceroute
      - unzip
      - usbutils
      - wavemon
      - whois
      - yamllint

- name: install VSCode
  become: true
  dnf:
    name: code

- name: install python utilities
  become: true
  dnf:
    name:
      - python3-ansible-lint
