---
- name: template systemd charge control unit
  become: true
  template:
    src: battery_thresholds.service.j2
    dest: /etc/systemd/system/battery_thresholds.service
    owner: root
    group: root
    mode: 0644

- name: enable systemd charge control unit
  become: true
  systemd:
    name: battery_thresholds
    enabled: true

- name: template apple mfi fastcharge udev rule
  become: true
  template:
    src: 99-ios-fastcharge.rules.j2
    dest: /etc/udev/rules.d/99-ios-fastcharge.rules.j2
    owner: root
    group: root
    mode: 0644
